{{- if .Values.balancingAgent.prometheus.prometheusRule.install -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.balancingAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ default .Release.Namespace .Values.balancingAgent.prometheus.prometheusRule.namespace }}
  labels:
    {{- include "project.balancingAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.balancingAgent.prometheus.prometheusRule.labels }}
    {{- include "tplvalues.render" ( dict "value" .Values.balancingAgent.prometheus.prometheusRule.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.balancingAgent.prometheus.prometheusRule.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.balancingAgent.prometheus.prometheusRule.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.balancingAgent.prometheus.prometheusRule.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  groups: []
{{- end }}
---
{{- if .Values.balancingController.prometheus.prometheusRule.install -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.balancingController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ default .Release.Namespace .Values.balancingController.prometheus.prometheusRule.namespace }}
  labels:
    {{- include "project.balancingController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.balancingController.prometheus.prometheusRule.labels }}
    {{- include "tplvalues.render" ( dict "value" .Values.balancingController.prometheus.prometheusRule.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.balancingController.prometheus.prometheusRule.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.balancingController.prometheus.prometheusRule.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.balancingController.prometheus.prometheusRule.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  groups: []
{{- end }}
