{{- if .Values.elfAgent.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elfAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.global.commonAnnotations .Values.elfAgent.service.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.elfAgent.service.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.elfAgent.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "project.elfAgent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elfAgent.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.elfAgent.prometheus.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "project.elfAgent.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elfController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.global.commonAnnotations .Values.elfController.service.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.elfController.service.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.elfController.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "project.elfController.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elfController.service.type }}
  ports:
    {{- if .Values.elfController.prometheus.enabled }}
    - name: metrics
      port: {{ .Values.elfController.prometheus.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    - name: webhook
      port: {{ .Values.elfController.webhookPort }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "project.elfController.selectorLabels" . | nindent 4 }}
