{{- if .Values.balancingAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.balancingAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.balancingAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.balancingAgent.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.balancingAgent.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.balancingAgent.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- if .Values.balancingController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.balancingController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.balancingController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.balancingController.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.balancingController.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.balancingController.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
