{{- if .Values.elfAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.elfAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.elfAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.elfAgent.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.elfAgent.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.elfAgent.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- if .Values.elfController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.elfController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.elfController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.elfController.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.elfController.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.elfController.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
