// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BalancingPolicyListerExpansion allows custom methods to be added to
// BalancingPolicyLister.
type BalancingPolicyListerExpansion interface{}

// LocalRedirectPolicyListerExpansion allows custom methods to be added to
// LocalRedirectPolicyLister.
type LocalRedirectPolicyListerExpansion interface{}
