// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/elf-io/balancing/pkg/k8s/apis/balancing.elf.io/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// LocalRedirectPolicyLister helps list LocalRedirectPolicies.
// All objects returned here must be treated as read-only.
type LocalRedirectPolicyLister interface {
	// List lists all LocalRedirectPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.LocalRedirectPolicy, err error)
	// Get retrieves the LocalRedirectPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.LocalRedirectPolicy, error)
	LocalRedirectPolicyListerExpansion
}

// localRedirectPolicyLister implements the LocalRedirectPolicyLister interface.
type localRedirectPolicyLister struct {
	listers.ResourceIndexer[*v1beta1.LocalRedirectPolicy]
}

// NewLocalRedirectPolicyLister returns a new LocalRedirectPolicyLister.
func NewLocalRedirectPolicyLister(indexer cache.Indexer) LocalRedirectPolicyLister {
	return &localRedirectPolicyLister{listers.New[*v1beta1.LocalRedirectPolicy](indexer, v1beta1.Resource("localredirectpolicy"))}
}
