#!/bin/bash

VM_NAME=${1:-"k8s-master"}
shift
EXEC_COMMAND="$@"

SSH_PORT=$(vagrant ssh-config ${VM_NAME} | grep Port | awk '{print $2}')
if [ -z "${EXEC_COMMAND}" ] ; then
  sshpass -p vagrant \
      ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@127.0.0.1
else
  echo "exec commmand: ${EXEC_COMMAND}"
  sshpass -p vagrant \
      ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@127.0.0.1 "${EXEC_COMMAND}"
fi
