// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/elf-io/balancing/pkg/k8s/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BalancingPolicies returns a BalancingPolicyInformer.
	BalancingPolicies() BalancingPolicyInformer
	// LocalRedirectPolicies returns a LocalRedirectPolicyInformer.
	LocalRedirectPolicies() LocalRedirectPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BalancingPolicies returns a BalancingPolicyInformer.
func (v *version) BalancingPolicies() BalancingPolicyInformer {
	return &balancingPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalRedirectPolicies returns a LocalRedirectPolicyInformer.
func (v *version) LocalRedirectPolicies() LocalRedirectPolicyInformer {
	return &localRedirectPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
