site_name: Balancing
docs_dir: docs
site_dir: site
repo_name: elf-io/balancing
site_url: https://elf-io.github.io/balancing/
repo_url: https://github.com/elf-io/balancing
remote_branch: github_pages
theme:
  name: material
  navigation_depth: 2
  features:
    - content.code.annotate
    - content.tabs.link
  palette:
    scheme: default
    primary: "#4478D1"
#  features:
#    - navigation.instant
#    - navigation.tracking
#    - navigation.indexes
#    - navigation.top
#    - search.highlight
#    - search.suggest
#    - search.share

extra:
  version:
    provider: mike

plugins:
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      material_alternate: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
  - tags
  - search

markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - tables
  - attr_list
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets

nav:
  - Overview: readme.md
  - Getting started:
      - Install: usage/install.md
      - Service: usage/service.md
      - LocalRedirect: usage/localredirect.md
      - Balancing: usage/balancing.md
  - Development:
      - Development： develop/develop.md
      - Debug： develop/ebufDebug.md
