# docker build -t myproxy -f Dockerfile.proxy .
# docker run -p 80:80 myproxy

FROM golang:1.24.3 AS builder

WORKDIR /app
COPY ./src .
RUN go build -o proxy_server proxy_server.go

#======================
FROM ubuntu:24.10

COPY --from=builder /app/proxy_server /usr/sbin
RUN chmod +x /usr/sbin/proxy_server
RUN apt update && apt install -y curl jq

EXPOSE 80
CMD ["sh", "-c", "/usr/sbin/proxy_server -port 80"]
