# docker build -t myproxy -f Dockerfile.proxy .
# docker run -p 80:80 myproxy

FROM golang:1.23.1 AS builder

WORKDIR /app
COPY ./src .
RUN go build -o proxy_server proxy_server.go

#======================
FROM ubuntu:24.10

ARG APT_HTTP_PROXY
RUN [ -z "${APT_HTTP_PROXY}" ] || { echo "use APT_HTTP_PROXY=${APT_HTTP_PROXY}" ; export http_proxy=${APT_HTTP_PROXY} ; } ; \
    apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/proxy_server /usr/sbin

EXPOSE 80
CMD ["sh", "-c", "/usr/sbin/proxy_server -port 80"]
