# docker build -t myproxy -f Dockerfile.proxy .
# docker run -p 80:80 myproxy

FROM golang:1.23.1 AS builder

WORKDIR /app
COPY / .

RUN go build -o proxy_server /app/tests/appServer/src/proxy_server.go

#======================
FROM ubuntu:24.10

COPY --from=builder /app/tests/appServer/src/proxy_server /usr/sbin
RUN chmod +x /usr/sbin/proxy_server

EXPOSE 80
CMD ["sh", "-c", "/usr/sbin/proxy_server -port 80"]
